const { withAppBuildGradle } = require('@expo/config-plugins');

// Config plugin: persists the Android RELEASE signing config across
// `expo prebuild`. The android/ folder is gitignored and regenerated by
// prebuild, which would otherwise reset release signing back to the debug key.
// This re-injects a `release` signingConfig that reads android/keystore.properties
// (the shared h2h-release.keystore) on every prebuild — so release APKs keep the
// production signature instead of being debug-signed. Idempotent.

const KEYSTORE_LOADER =
  '\n\n' +
  'def keystorePropertiesFile = rootProject.file("keystore.properties")\n' +
  'def keystoreProperties = new Properties()\n' +
  'if (keystorePropertiesFile.exists()) {\n' +
  '    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))\n' +
  '}';

const RELEASE_SIGNING_CONFIG =
  "        release {\n" +
  "            if (keystoreProperties['storeFile']) {\n" +
  "                storeFile file(keystoreProperties['storeFile'])\n" +
  "                storePassword keystoreProperties['storePassword']\n" +
  "                keyAlias keystoreProperties['keyAlias']\n" +
  "                keyPassword keystoreProperties['keyPassword']\n" +
  "            }\n" +
  "        }\n";

/** Pure transform — exported for testing without running a full prebuild. */
function applyReleaseSigning(contents) {
  let gradle = contents;

  // 1) Load keystore.properties (once), right after the projectRoot def.
  if (!gradle.includes('keystorePropertiesFile')) {
    gradle = gradle.replace(/^(def projectRoot = .*)$/m, `$1${KEYSTORE_LOADER}`);
  }

  // 2) Add a `release` signingConfig inside signingConfigs { } (once).
  //    Keyed on the unique storeFile lookup so we never double-insert.
  if (!gradle.includes("keystoreProperties['storeFile']")) {
    gradle = gradle.replace(/(signingConfigs\s*\{\s*\n)/, `$1${RELEASE_SIGNING_CONFIG}`);
  }

  // 3) Point the release buildType at the release signingConfig (not debug).
  gradle = gradle.replace(
    /(buildTypes\s*\{[\s\S]*?\brelease\s*\{[\s\S]*?signingConfig\s+)signingConfigs\.debug/,
    '$1signingConfigs.release',
  );

  return gradle;
}

const withReleaseSigning = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        'withReleaseSigning is only supported for build.gradle (groovy) projects.',
      );
    }
    cfg.modResults.contents = applyReleaseSigning(cfg.modResults.contents);
    return cfg;
  });

module.exports = withReleaseSigning;
module.exports.applyReleaseSigning = applyReleaseSigning;
